[install]
minimumReleaseAge = 259200
minimumReleaseAgeExcludes = [
  "@fastly/mcp",
  "fastly",
  "fast-cipher",
  "@modelcontextprotocol/server",
  "@modelcontextprotocol/node",
  "@modelcontextprotocol/core",
  "@modelcontextprotocol/client",
]
